// The area's words in Italian: every string the patient reads.
export default {
  'Your area': 'La tua area',
  'Enter with your email': 'Entra con la tua email',
  'We send you a code: no password to remember.':
    'Ti mandiamo un codice: nessuna password da ricordare.',
  Email: 'Email',
  'Send me the code': 'Mandami il codice',
  'If this address has an area, a code is on its way. It is valid for {0} minutes.':
    'Se questo indirizzo ha un’area, il codice sta arrivando. Vale {0} minuti.',
  'The code': 'Il codice',
  Enter: 'Entra',
  'Another address': 'Un altro indirizzo',
  'Send it again': 'Mandalo di nuovo',
  'This area is for the patients of the centre.':
    'Quest’area è per i pazienti del centro.',
  'Your work is in the CRM.': 'Il tuo lavoro è nel CRM.',
  'Open the CRM': 'Apri il CRM',
  Home: 'Inizio',
  Appointments: 'Appuntamenti',
  Documents: 'Documenti',
  Invoices: 'Fatture',
  'Log out': 'Esci',
  'Hello, {0}': 'Ciao, {0}',
  'Your next appointment': 'Il tuo prossimo appuntamento',
  'No appointments booked.': 'Nessun appuntamento prenotato.',
  'Move or cancel': 'Sposta o annulla',
  'Coming up': 'In programma',
  Past: 'Passati',
  'Nothing here yet.': 'Qui non c’è ancora niente.',
  'With {0}': 'Con {0}',
  Cancelled: 'Annullato',
  Completed: 'Svolto',
  'Documents the centre gave you, online until the date shown.':
    'I documenti che il centro ti ha dato, online fino alla data indicata.',
  'Online until {0}': 'Online fino al {0}',
  Download: 'Scarica',
  Downloaded: 'Scaricato',
  'To download a document we send you a code again.':
    'Per scaricare un documento ti mandiamo di nuovo un codice.',
  Cancel: 'Annulla',
  'Invoice {0}': 'Fattura {0}',
  'PDF not ready': 'PDF non ancora pronto',
  'Whose area': 'Di chi è l’area',
  'Something went wrong: try again.': 'Qualcosa non è andato: riprova.',
  'The code has expired: ask for a new one':
    'Il codice è scaduto: chiedine uno nuovo',
  'Too many wrong codes: ask for a new one':
    'Troppi codici sbagliati: chiedine uno nuovo',
  'The code is not right': 'Il codice non è giusto',
  'This area is closed: ask the centre':
    'Quest’area è chiusa: chiedi al centro',
  'Write your email address': 'Scrivi il tuo indirizzo email',
  Report: 'Referto',
  'External report': 'Referto esterno',
  'Test result': 'Esame',
  Imaging: 'Immagine',
  Prescription: 'Prescrizione',
  'Signed form': 'Modulo firmato',
  Other: 'Altro',
  'Your documents': 'I tuoi documenti',
  'Your invoices': 'Le tue fatture',
  'Your appointments': 'I tuoi appuntamenti',
  'Documents online': 'Documenti online',
  'See all': 'Vedi tutti',
  Messages: 'Messaggi',
  'Prepare your visit': 'Prepara la visita',
  'Before your appointment of {0}': 'Prima del tuo appuntamento del {0}',
  Started: 'Iniziato',
  'To fill': 'Da compilare',
  Continue: 'Continua',
  Fill: 'Compila',
  'There is nothing to fill here': 'Qui non c’è niente da compilare',
  'To sign at the centre': 'Da firmare al centro',
  'Your forms are answered by a parent or guardian, from their area':
    'I tuoi moduli li compila un genitore o il tutore, dalla sua area',
  'To sign for them, ask the centre to add you to their related people':
    'Per firmare al suo posto, chiedi al centro di aggiungerti tra le sue persone collegate',
  'The person signs their own forms': 'I moduli li firma la persona stessa',
  Agenda: 'Agenda',
  Plans: 'Piani',
  'Your plans': 'I tuoi piani',
  'Today {0} of {1}': 'Oggi {0} su {1}',
  'No plan to follow now.': 'Nessun piano da seguire adesso.',
  'What to keep in mind': 'Da tenere a mente',
  Today: 'Oggi',
  'A look ahead: you mark it on the day.':
    'Uno sguardo avanti: lo segni il giorno stesso.',
  'Nothing planned for this day.': 'Niente in programma per questo giorno.',
  Done: 'Fatto',
  Partly: 'In parte',
  Skipped: 'Saltato',
  'Or instead: {0}': 'Oppure: {0}',
  'Still {0} this week': 'Ancora {0} questa settimana',
  'Done for this week': 'Fatto per questa settimana',
  'Choose among': 'Scegli tra',
  'How to do it': 'Come si fa',
  'Watch the video': 'Guarda il video',
  'Meal plan': 'Piano alimentare',
  'Exchange diet': 'Dieta a scambi',
  Training: 'Allenamento',
  'Home exercises': 'Esercizi a casa',
  Habits: 'Abitudini',
  '{0} times a week': '{0} volte a settimana',
  '{0} portion of {1}': '{0} porzione di {1}',
  '{0} portions of {1}': '{0} porzioni di {1}',
  '{0} sets': '{0} serie',
  'rest {0}': 'recupero {0}',
  Food: 'Alimento',
  Exercise: 'Esercizio',
  'Cereals and tubers': 'cereali e tuberi',
  Legumes: 'legumi',
  Meat: 'carne',
  Fish: 'pesce',
  Eggs: 'uova',
  'Milk and dairy': 'latte e latticini',
  Vegetables: 'verdura',
  Fruit: 'frutta',
  'Oils and fats': 'oli e grassi',
  'Nuts and seeds': 'frutta secca e semi',
  Sweets: 'dolci',
  Drinks: 'bevande',
  'This plan is not followed now': 'Questo piano non è in corso',
  'Shopping list': 'Lista della spesa',
  'A week': 'Una settimana',
  'Two weeks': 'Due settimane',
  'From {0} to {1}': 'Dal {0} al {1}',
  'the plan ends before': 'il piano finisce prima',
  '{0} g, {1} times': '{0} g, {1} volte',
  '{0} times': '{0} volte',
  'To choose in the group': 'Da scegliere nel gruppo',
  'Nothing to buy in these days.': 'Niente da comprare in questi giorni.',
  'Untick everything': 'Togli tutte le spunte',
  'Only a diet has a shopping list': 'Solo una dieta ha la lista della spesa',
  'This day is not shown': 'Questo giorno non si vede',
  'Your programmes': 'I tuoi percorsi',
  'Stage {0} of {1}': 'Tappa {0} di {1}',
  'All stages done': 'Tutte le tappe fatte',
  'Not started yet': 'Non ancora iniziato',
  'Opens on {0}': 'Si apre il {0}',
  'Opens when you finish the one before': 'Si apre quando finisci quella prima',
  'Open the plan of this stage': 'Apri il piano di questa tappa',
  'I have finished this stage': 'Ho finito questa tappa',
  'The next stage opens now.': 'La tappa dopo si apre adesso.',
  'This is the last stage.': 'È l’ultima tappa.',
  'Yes, finished': 'Sì, finita',
  'Not yet': 'Non ancora',
  Open: 'Aperta',
  'Not open yet': 'Non ancora aperta',
  'This programme is not followed now': 'Questo percorso non è in corso',
  'In this programme the stages open by themselves, on their day':
    'In questo percorso le tappe si aprono da sole, nel loro giorno',
  'This stage is not the one open': 'Questa non è la tappa aperta',
  // cycles of sessions
  'Your cycles of sessions': 'I tuoi cicli di sedute',
  'Sessions used': 'Sedute usate',
  '{0} of {1} done': '{0} di {1} fatte',
  '{0} booked': '{0} prenotate',
  '{0} missed': '{0} perse',
  'Nothing left to book': 'Sono tutte prenotate',
  '1 session to book': '1 seduta da prenotare',
  '{0} sessions to book': '{0} sedute da prenotare',
  'valid until {0}': 'valido fino al {0}',
  'Session {0} of {1}': 'Seduta {0} di {1}',
}
