// The area's words in Italian: every string its people read, and the words a
// vertical says its own way (the clinic's, in crm/clinica/parole.py).
export default {
  'Your area': 'La tua area',
  'Enter your area': 'Entra nella tua area',
  'Enter with your email': 'Entra con la tua email',
  'We send you a code: no password to remember.':
    'Ti mandiamo un codice: nessuna password da ricordare.',
  Email: 'Email',
  'Send me the code': 'Mandami il codice',
  'If this address has an area, a code is on its way. It is valid for {0} minutes.':
    'Se questo indirizzo ha un’area, il codice sta arrivando. Vale {0} minuti.',
  'The code': 'Il codice',
  Enter: 'Entra',
  'Another address': 'Un altro indirizzo',
  'Send it again': 'Mandalo di nuovo',
  "This area is for the centre's clients.":
    'Quest’area è per i clienti del centro.',
  "This area is for the centre's patients.":
    'Quest’area è per i pazienti del centro.',
  'Your work is in {brand}.': 'Il tuo lavoro è in {brand}.',
  'Powered by {brand}': 'Con tecnologia {brand}',
  'Open {brand}': 'Apri {brand}',
  Appointments: 'Appuntamenti',
  Documents: 'Documenti',
  Invoices: 'Fatture',
  'Log out': 'Esci',
  'Hello, {0}': 'Ciao, {0}',
  'Your next appointment': 'Il tuo prossimo appuntamento',
  'No appointments booked.': 'Nessun appuntamento prenotato.',
  'Move or cancel': 'Sposta o annulla',
  'Coming up': 'In programma',
  Past: 'Passati',
  'Nothing here yet.': 'Qui non c’è ancora niente.',
  'With {0}': 'Con {0}',
  Cancelled: 'Annullato',
  Completed: 'Svolto',
  'Documents the centre gave you, online until the date shown.':
    'I documenti che il centro ti ha dato, online fino alla data indicata.',
  'Online until {0}': 'Online fino al {0}',
  Download: 'Scarica',
  Downloaded: 'Scaricato',
  'To download a document we send you a code again.':
    'Per scaricare un documento ti mandiamo di nuovo un codice.',
  Cancel: 'Annulla',
  'Invoice {0}': 'Fattura {0}',
  'PDF not ready': 'PDF non ancora pronto',
  'To pay': 'Da pagare',
  'To pay: {0}': 'Da pagare: {0}',
  'How to pay': 'Come pagare',
  'Whose area': 'Di chi è l’area',
  'Something went wrong: try again.': 'Qualcosa non è andato: riprova.',
  'The code has expired: ask for a new one':
    'Il codice è scaduto: chiedine uno nuovo',
  'Too many wrong codes: ask for a new one':
    'Troppi codici sbagliati: chiedine uno nuovo',
  'The code is not right': 'Il codice non è giusto',
  'The link of your email enters your area: tap Enter.':
    'Il link della tua email ti fa entrare nella tua area: tocca Entra.',
  'This link no longer works: write your email and we send you a code':
    'Questo link non vale più: scrivi la tua email e ti mandiamo un codice',
  'This area is closed: ask the centre':
    'Quest’area è chiusa: chiedi al centro',
  'Write your email address': 'Scrivi il tuo indirizzo email',
  Report: 'Referto',
  'External report': 'Referto esterno',
  'Test result': 'Esame',
  Imaging: 'Immagine',
  Prescription: 'Prescrizione',
  'Signed form': 'Modulo firmato',
  Other: 'Altro',
  'Your documents': 'I tuoi documenti',
  'Your invoices': 'Le tue fatture',
  'Your appointments': 'I tuoi appuntamenti',
  'Documents online': 'Documenti online',
  'See all': 'Vedi tutti',
  Messages: 'Messaggi',
  'Prepare your appointment': 'Prepara l’appuntamento',
  'Forms to fill in': 'Moduli da compilare',
  'Prepare your visit': 'Prepara la visita',
  'Before your appointment of {0}': 'Prima del tuo appuntamento del {0}',
  Started: 'Iniziato',
  'To fill': 'Da compilare',
  Continue: 'Continua',
  Fill: 'Compila',
  'There is nothing to fill here': 'Qui non c’è niente da compilare',
  'To sign at the centre': 'Da firmare al centro',
  'Your forms are answered by a parent or guardian, from their area':
    'I tuoi moduli li compila un genitore o il tutore, dalla sua area',
  'To sign for them, ask the centre to add you to their related people':
    'Per firmare al suo posto, chiedi al centro di aggiungerti tra le sue persone collegate',
  'The person signs their own forms': 'I moduli li firma la persona stessa',
  Agenda: 'Agenda',
  Plans: 'Piani',
  'Your plans': 'I tuoi piani',
  'Today {0} of {1}': 'Oggi {0} su {1}',
  'No plan to follow now.': 'Nessun piano da seguire adesso.',
  'What to keep in mind': 'Da tenere a mente',
  Today: 'Oggi',
  'A look ahead: you mark it on the day.':
    'Uno sguardo avanti: lo segni il giorno stesso.',
  'Nothing planned for this day.': 'Niente in programma per questo giorno.',
  Done: 'Fatto',
  Partly: 'In parte',
  Skipped: 'Saltato',
  'Or instead: {0}': 'Oppure: {0}',
  'Still {0} this week': 'Ancora {0} questa settimana',
  'Done for this week': 'Fatto per questa settimana',
  'Choose among': 'Scegli tra',
  'How to do it': 'Come si fa',
  'Watch the video': 'Guarda il video',
  'Meal plan': 'Piano alimentare',
  'Exchange diet': 'Dieta a scambi',
  Training: 'Allenamento',
  'Home exercises': 'Esercizi a casa',
  Habits: 'Abitudini',
  '{0} times a week': '{0} volte a settimana',
  '{0} portion of {1}': '{0} porzione di {1}',
  '{0} portions of {1}': '{0} porzioni di {1}',
  '{0} sets': '{0} serie',
  'rest {0}': 'recupero {0}',
  Food: 'Alimento',
  Exercise: 'Esercizio',
  'Cereals and tubers': 'cereali e tuberi',
  Legumes: 'legumi',
  Meat: 'carne',
  Fish: 'pesce',
  Eggs: 'uova',
  'Milk and dairy': 'latte e latticini',
  Vegetables: 'verdura',
  Fruit: 'frutta',
  'Oils and fats': 'oli e grassi',
  'Nuts and seeds': 'frutta secca e semi',
  Sweets: 'dolci',
  Drinks: 'bevande',
  'This plan is not followed now': 'Questo piano non è in corso',
  'Shopping list': 'Lista della spesa',
  'A week': 'Una settimana',
  'Two weeks': 'Due settimane',
  'From {0} to {1}': 'Dal {0} al {1}',
  'the plan ends before': 'il piano finisce prima',
  '{0} g, {1} times': '{0} g, {1} volte',
  '{0} times': '{0} volte',
  'To choose in the group': 'Da scegliere nel gruppo',
  'Nothing to buy in these days.': 'Niente da comprare in questi giorni.',
  'Untick everything': 'Togli tutte le spunte',
  'Only a diet has a shopping list': 'Solo una dieta ha la lista della spesa',
  'This day is not shown': 'Questo giorno non si vede',
  'Your programmes': 'I tuoi percorsi',
  'Stage {0} of {1}': 'Tappa {0} di {1}',
  'All stages done': 'Tutte le tappe fatte',
  'Not started yet': 'Non ancora iniziato',
  'Opens on {0}': 'Si apre il {0}',
  'Opens when you finish the one before': 'Si apre quando finisci quella prima',
  'Open the plan of this stage': 'Apri il piano di questa tappa',
  'I have finished this stage': 'Ho finito questa tappa',
  'The next stage opens now.': 'La tappa dopo si apre adesso.',
  'This is the last stage.': 'È l’ultima tappa.',
  'Yes, finished': 'Sì, finita',
  'Not yet': 'Non ancora',
  Open: 'Aperta',
  'Not open yet': 'Non ancora aperta',
  'This programme is not followed now': 'Questo percorso non è in corso',
  'In this programme the stages open by themselves, on their day':
    'In questo percorso le tappe si aprono da sole, nel loro giorno',
  'This stage is not the one open': 'Questa non è la tappa aperta',
  // cycles of sessions
  'Your cycles of sessions': 'I tuoi cicli di sedute',
  'Sessions used': 'Sedute usate',
  // subscriptions
  'Your subscriptions': 'I tuoi abbonamenti',
  Suspended: 'Sospeso',
  'Entries used': 'Ingressi usati',
  '1 entry left this week': '1 ingresso rimasto questa settimana',
  '1 entry left this month': '1 ingresso rimasto questo mese',
  '{0} entries left this week': '{0} ingressi rimasti questa settimana',
  '{0} entries left this month': '{0} ingressi rimasti questo mese',
  'suspended until {0}': 'sospeso fino al {0}',
  'renews by itself on {0}': 'rinnovo automatico: {0}',
  '{0} of {1} done': '{0} di {1} fatte',
  '{0} booked': '{0} prenotate',
  '{0} missed': '{0} perse',
  'Nothing left to book': 'Sono tutte prenotate',
  '1 session to book': '1 seduta da prenotare',
  '{0} sessions to book': '{0} sedute da prenotare',
  'valid until {0}': 'valido fino al {0}',
  'Session {0} of {1}': 'Seduta {0} di {1}',
  // quotes, and the dental care plans among them
  'Your quotes': 'I tuoi preventivi',
  'To decide': 'Da decidere',
  'Going on': 'In corso',
  'The quote is valid until {0}.': 'Il preventivo vale fino al {0}.',
  'To do': 'Da fare',
  'Booked for {0}': 'Prenotato per {0}',
  Total: 'Totale',
  'Done so far': 'Fatto finora',
  // the waiting list
  'Waiting list': 'Lista d’attesa',
  'Join the waiting list': 'Mettiti in lista d’attesa',
  'No time suits you? Join the waiting list: when a place frees up we write to you.':
    'Nessun orario va bene? Mettiti in lista d’attesa: quando si libera un posto ti scriviamo.',
  'A place for you': 'Un posto per te',
  Waiting: 'In attesa',
  'It is yours if you confirm by {0}': 'È tuo se confermi entro {0}',
  'Yes, book it': 'Sì, prenotalo',
  'No thanks': 'No, grazie',
  'When a place frees up we write to you: it goes to whoever confirms first.':
    'Quando si libera un posto ti scriviamo: va a chi conferma per primo.',
  'Leave the waiting list': 'Esci dalla lista d’attesa',
  'You are no longer on the waiting list for {0}.':
    'Non sei più in lista d’attesa per {0}.',
  'A seat in the class of {0}': 'Un posto nella lezione di {0}',
  'until {0}': 'fino al {0}',
  'Booked: you find it among your appointments.':
    'Prenotato: lo trovi fra i tuoi appuntamenti.',
  'Somebody confirmed before you: the place has gone. You are still on the list.':
    'Qualcuno ha confermato prima di te: il posto non c’è più. Resti in lista.',
  'The time to answer has passed: the place went to the next person. You are still on the list.':
    'Il tempo per rispondere è passato: il posto è andato a chi aspetta dopo di te. Resti in lista.',
  'Fine: the place goes to the next person. You keep your place on the list.':
    'Va bene: il posto va a chi aspetta dopo di te. Resti in lista.',
  'Choose the days and times you can: when a place frees up there we write to you, and it goes to whoever confirms first.':
    'Scegli i giorni e le ore in cui puoi: quando lì si libera un posto ti scriviamo, e va a chi conferma per primo.',
  Service: 'Servizio',
  'Choose a service': 'Scegli un servizio',
  With: 'Con',
  Anybody: 'Chiunque',
  Days: 'Giorni',
  'Times of day': 'Parti del giorno',
  Morning: 'Mattina',
  Afternoon: 'Pomeriggio',
  Evening: 'Sera',
  'Nothing chosen: any day, any time.':
    'Nessuna scelta: qualsiasi giorno, a qualsiasi ora.',
  Until: 'Fino al',
  'Write to me by': 'Scrivimi su',
  'Put me on the list': 'Mettimi in lista',
  'Any day, any time': 'Qualsiasi giorno, a qualsiasi ora',
  'Any day': 'Qualsiasi giorno',
  'Any time': 'A qualsiasi ora',
  // The chat with the centre's assistant, entering with a passkey, the news.
  'Ask the centre': 'Chiedi al centro',
  'This is the centre’s virtual assistant, an AI, not a person. It answers about opening hours, bookings and the centre’s frequent questions. It does not answer about your health: it offers to pass your question to a person. In an emergency call 112.':
    'Questo è l’assistente virtuale del centro, un’intelligenza artificiale, non una persona. Risponde su orari, prenotazioni e domande frequenti del centro. Non risponde sulla tua salute: ti propone di passare la domanda a una persona. In un’emergenza chiama il 112.',
  'Call 112': 'Chiama il 112',
  'AI answer': 'Risposta dell’intelligenza artificiale',
  'Automatic answer': 'Risposta automatica',
  'Pass my question to the centre': 'Passa la mia domanda al centro',
  'Passed to the centre: the answer comes in':
    'Passata al centro: la risposta arriva in',
  'Writing…': 'Sta scrivendo…',
  'Your question about hours or bookings':
    'La tua domanda su orari o prenotazioni',
  'Your question': 'La tua domanda',
  Send: 'Invia',
  'A question about hours or bookings?': 'Una domanda su orari o prenotazioni?',
  'Ask the centre’s virtual assistant, an AI':
    'Chiedi all’assistente virtuale del centro, un’intelligenza artificiale',
  'Ask the assistant': 'Chiedi all’assistente',
  'read by the centre': 'letta dal centro',
  'not read by the centre yet': 'non ancora letta dal centro',
  or: 'oppure',
  'Enter with a passkey': 'Entra con una passkey',
  'Entering with a passkey': 'Entrare con una passkey',
  'Next time, enter with your face or fingerprint instead of a code. The key stays on this phone.':
    'La prossima volta entra con il volto o l’impronta invece del codice. La chiave resta su questo telefono.',
  'Add a passkey': 'Aggiungi una passkey',
  'Not now': 'Non ora',
  'On your home screen': 'Sulla schermata Home',
  'Add the area to your home screen: it opens like an app, without the browser.':
    'Aggiungi l’area alla schermata Home: si apre come un’app, senza il browser.',
  'In Safari tap Share, then «Add to Home Screen».':
    'In Safari tocca Condividi, poi «Aggiungi alla schermata Home».',
  'Open the browser’s menu (⋮), then «Install app» or «Add to Home screen».':
    'Apri il menu del browser (⋮), poi «Installa app» o «Aggiungi a schermata Home».',
  Install: 'Installa',
  'used {0}': 'usata il {0}',
  'added {0}': 'aggiunta il {0}',
  Remove: 'Togli',
  'Add one on another device': 'Aggiungine una su un altro dispositivo',
  'How we tell you there is news': 'Come ti avvisiamo delle novità',
  'We only say that there is news in your area, never what it is. By email always, to {0}.':
    'Ti diciamo solo che c’è una novità nella tua area, mai di cosa si tratta. Per email sempre, a {0}.',
  'Also on {0}': 'Anche su {0}',
  'to your number {0}': 'al tuo numero {0}',
  'Write to the centre once on {0} from your number, then you can turn this on.':
    'Scrivi una volta al centro su {0} dal tuo numero, poi potrai attivarlo.',
  // the centre's preview of a person's area (crm.area.anteprima)
  'Close the preview': 'Chiudi l’anteprima',
  'Preview: this is the area of {0} as they see it. Nothing is changed or sent from here.':
    'Anteprima: questa è l’area di {0} come la vede. Da qui non si cambia e non si manda niente.',
  'Here {0} sees something you do not read in {brand}.':
    'Qui {0} vede qualcosa che in {brand} tu non leggi.',
  'In the preview the chat does not answer.':
    'Nell’anteprima la chat non risponde.',
  '{0} rusk': '{0} fetta biscottata',
  '{0} rusks': '{0} fette biscottate',
  '{0} biscuit': '{0} biscotto',
  '{0} biscuits': '{0} biscotti',
  '{0} slice': '{0} fetta',
  '{0} slices': '{0} fette',
  '{0} egg': '{0} uovo',
  '{0} eggs': '{0} uova',
  '{0} jar': '{0} vasetto',
  '{0} jars': '{0} vasetti',
  '{0} teaspoon': '{0} cucchiaino',
  '{0} teaspoons': '{0} cucchiaini',
  '{0} tablespoon': '{0} cucchiaio',
  '{0} tablespoons': '{0} cucchiai',
  '{0} glass': '{0} bicchiere',
  '{0} glasses': '{0} bicchieri',
  '{0} handful': '{0} manciata',
  '{0} handfuls': '{0} manciate',
  '{0} medium fruit': '{0} frutto medio',
  '{0} medium fruits': '{0} frutti medi',
  'each side': 'per lato',
  'left side': 'lato sinistro',
  'right side': 'lato destro',
  'How hard or painful was it?': 'Quanto è stato faticoso o doloroso?',
  '{0} out of 10': '{0} su 10',
  '1 hardly': '1 per niente',
  '10 very much': '10 moltissimo',
  'I’m here': 'Sono qui',
  'You are in the waiting room: the centre knows you are here.':
    'Sei in sala d’attesa: il centro sa che sei qui.',
  'Book again': 'Prenota di nuovo',
  'Book an appointment': 'Prenota un appuntamento',
  // a quote answered in the area (crm.preventivi.firma)
  'This quote was valid until {0}: ask the centre for a new one.':
    'Questo preventivo valeva fino al {0}: chiedine uno nuovo al centro.',
  'Accepted and signed on {0}.': 'Accettato e firmato il {0}.',
  'Signed copy': 'Copia firmata',
  'Read the PDF': 'Leggi il PDF',
  'I do not accept': 'Non accetto',
  'Accept and sign': 'Accetta e firma',
  'By signing you accept the quote as it is, at the prices shown. The centre receives your signature and you get a signed copy here.':
    'Firmando accetti il preventivo così com’è, ai prezzi indicati. Il centro riceve la tua firma e qui trovi una copia firmata.',
  'Read the quote (PDF)': 'Leggi il preventivo (PDF)',
  'Sign here with your finger': 'Firma qui con il dito',
  'Sign and accept': 'Firma e accetta',
  'We tell the centre you do not accept «{0}». If you want, say why: it helps them propose something else.':
    'Diciamo al centro che non accetti «{0}». Se vuoi, scrivi perché: lo aiuta a proporti qualcos’altro.',
  'Why (if you want)': 'Perché (se vuoi)',
  'We told the centre you do not accept «{0}».':
    'Abbiamo detto al centro che non accetti «{0}».',
  'Not signed': 'Non firmato',
  'Sign again': 'Firma di nuovo',
  Clear: 'Cancella',
  'To sign we send you a code again: it says the signature is yours.':
    'Per firmare ti mandiamo di nuovo un codice: dice che la firma è tua.',
}
