// The area's words in Italian: every string the patient reads.
export default {
  'Your area': 'La tua area',
  'Enter with your email': 'Entra con la tua email',
  'We send you a code: no password to remember.':
    'Ti mandiamo un codice: nessuna password da ricordare.',
  Email: 'Email',
  'Send me the code': 'Mandami il codice',
  'If this address has an area, a code is on its way. It is valid for {0} minutes.':
    'Se questo indirizzo ha un’area, il codice sta arrivando. Vale {0} minuti.',
  'The code': 'Il codice',
  Enter: 'Entra',
  'Another address': 'Un altro indirizzo',
  'Send it again': 'Mandalo di nuovo',
  'This area is for the patients of the centre.':
    'Quest’area è per i pazienti del centro.',
  'Your work is in the CRM.': 'Il tuo lavoro è nel CRM.',
  'Open the CRM': 'Apri il CRM',
  Home: 'Inizio',
  Appointments: 'Appuntamenti',
  Documents: 'Documenti',
  Invoices: 'Fatture',
  'Log out': 'Esci',
  'Hello, {0}': 'Ciao, {0}',
  'Your next appointment': 'Il tuo prossimo appuntamento',
  'No appointments booked.': 'Nessun appuntamento prenotato.',
  'Move or cancel': 'Sposta o annulla',
  'Coming up': 'In programma',
  Past: 'Passati',
  'Nothing here yet.': 'Qui non c’è ancora niente.',
  'With {0}': 'Con {0}',
  Cancelled: 'Annullato',
  Completed: 'Svolto',
  'Documents the centre gave you, online until the date shown.':
    'I documenti che il centro ti ha dato, online fino alla data indicata.',
  'Online until {0}': 'Online fino al {0}',
  Download: 'Scarica',
  Downloaded: 'Scaricato',
  'To download a document we send you a code again.':
    'Per scaricare un documento ti mandiamo di nuovo un codice.',
  Cancel: 'Annulla',
  'Invoice {0}': 'Fattura {0}',
  'PDF not ready': 'PDF non ancora pronto',
  'Whose area': 'Di chi è l’area',
  'Something went wrong: try again.': 'Qualcosa non è andato: riprova.',
  'The code has expired: ask for a new one':
    'Il codice è scaduto: chiedine uno nuovo',
  'Too many wrong codes: ask for a new one':
    'Troppi codici sbagliati: chiedine uno nuovo',
  'The code is not right': 'Il codice non è giusto',
  'This area is closed: ask the centre':
    'Quest’area è chiusa: chiedi al centro',
  'Write your email address': 'Scrivi il tuo indirizzo email',
  Report: 'Referto',
  'External report': 'Referto esterno',
  'Test result': 'Esame',
  Imaging: 'Immagine',
  Prescription: 'Prescrizione',
  'Signed form': 'Modulo firmato',
  Other: 'Altro',
  'Your documents': 'I tuoi documenti',
  'Your invoices': 'Le tue fatture',
  'Your appointments': 'I tuoi appuntamenti',
  'Documents online': 'Documenti online',
  'See all': 'Vedi tutti',
  Messages: 'Messaggi',
  'Prepare your visit': 'Prepara la visita',
  'Before your appointment of {0}': 'Prima del tuo appuntamento del {0}',
  Started: 'Iniziato',
  'To fill': 'Da compilare',
  Continue: 'Continua',
  Fill: 'Compila',
  'There is nothing to fill here': 'Qui non c’è niente da compilare',
  'To sign at the centre': 'Da firmare al centro',
  'Your forms are answered by a parent or guardian, from their area':
    'I tuoi moduli li compila un genitore o il tutore, dalla sua area',
  'To sign for them, ask the centre to add you to their related people':
    'Per firmare al suo posto, chiedi al centro di aggiungerti tra le sue persone collegate',
  'The person signs their own forms': 'I moduli li firma la persona stessa',
}
